### ISSUE TITLE
Problems related to Flatpak packaging

### ISSUE THREAD

**Issue by KelvinNovais** [flathub/org.musescore.MuseScore#127]
There are two problems that only happens with the Flatpak package:

1. musescore/MuseScore#21036
2. musescore/MuseScore#22206

Have in mind that these issues aren't found on the AppImage.
Apparently the developers won't support the Flatpak format, only AppImage; I think even the .deb and .rpm aren't supported anymore.

I tried to discover the problems, and the solution was replace the Ubuntu runtime/base versions with the following:

```diff
# org.musescore.MuseScore.yaml

---
app-id: org.musescore.MuseScore

base: io.qt.qtwebengine.BaseApp
- base-version: '5.15-23.08'
+ base-version: '5.15'

runtime: org.kde.Platform
- runtime-version: '5.15-23.08'
+ runtime-version: '5.15'
sdk: org.kde.Sdk

[...]
```

**However, these runtimes are end-of-life.** Do you think there is another solution?
Here is a short video with the results, everything is working fine:

https://github.com/flathub/org.musescore.MuseScore/assets/83086622/5b3b8ded-234e-40f6-8e49-9e7cfd555fe5

**Comment by hfiguiere** [comment]
You suggest to use a runtime that is EOL.

**Comment by hfiguiere** [comment]
the proper solution is to debug the code and find proper fixes.

**Comment by hfiguiere** [comment]
See also #119.

**Comment by KelvinNovais** [comment]
> You suggest to use a runtime that is EOL.

I'm aware of that, but I was wondering if there is another solution, because shouldn't `5.15-23.08` behave the same as `5.15`?
Trying to fix something that was supposed to work without problems is weird... will that be stable on new releases?

**Comment by KelvinNovais** [comment]
It seems that `org.kde.PlatformTheme.QGnomePlatform` is the root of the problem. Uninstalling it solves the theme and the panel issues...

Do you know if there's a way to disable it only in this package, instead of uninstalling?

**Comment by KelvinNovais** [comment]
I tried to override QT_QPA_PLATFORMTHEME, and also other things, but didn't solve. It lacks some documentation. 

I'm going to close this issue, since these bugs are already reported here and on [QGnomePlatform repository](https://github.com/FedoraQt/QGnomePlatform/issues/154).

Moreover, this project is currently unmaintained. I hope it can be replaced or fixed soon on future updates.
