### ISSUE TITLE
Include JACK

### ISSUE THREAD

**Issue by jurf** [flathub/org.musescore.MuseScore#25]

**Comment by jurf** [comment]
No longer? Since when? I thought it was possible if jackd was running on the host.

**Comment by TingPing** [comment]
It was broken in 1.0.3: https://github.com/flatpak/flatpak/commit/89e2b6679cd4a59c15b225c0c6c0e1293ae83f7d

See https://github.com/flatpak/flatpak/issues/1509

**Comment by jurf** [comment]
Closing until something changes on this front…
