### ISSUE TITLE
Update runtime to 5.13

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.musescore.MuseScore#39]

**Comment by jurf** [comment]
https://github.com/flathub/io.qt.qtwebkit.BaseApp/issues/18

**Comment by hfiguiere** [comment]
Still upstream doesn't build on this version :-(

**Comment by hfiguiere** [comment]
It needs qt5-webengine, and that seems to not be available in the SDK.

flathub/io.qt.qtwebengine.BaseApp would help but it is not available.

**Comment by hfiguiere** [comment]
io.qt.qtwebengine.BaseApp is available. I have a work in progress patch for that. But it needs fixing.
