### ISSUE TITLE
Update `Updated` and `Version` fields on Flathub

### ISSUE THREAD

**Issue by ovari** [flathub/org.musescore.MuseScore#44]
### MuseScore version 3.3.2 is on Flathub:
![image](https://user-images.githubusercontent.com/17465872/70211874-3f1cd000-178a-11ea-93d7-e02ed7bf0d0c.png)
https://github.com/flathub/org.musescore.MuseScore/commit/6e5a7806658f03de9a1e25b17f5e6a6bfb2e5cc7

### However, Flathub shows MuseScore version 3.2.3:
![image](https://user-images.githubusercontent.com/17465872/70211832-23b1c500-178a-11ea-8245-aaa9f89fd17e.png)
https://flathub.org/apps/details/org.musescore.MuseScore

This issue/pr/comment may be of assistance:
https://github.com/flathub/org.kde.skrooge/issues/10
https://github.com/flathub/org.kde.skrooge/commit/bb78b168fd95396c3cb877bd81aeb634a2bb1c19

What do you think?

Thank you

**Comment by jurf** [comment]
I mean, I _can_ patch it around, but the Appstream metadata is now in the hands of the MuseScore team, so it won’t solve anything long-term, I’d rather bring this to them.

**Comment by hfiguiere** [comment]
PR #45 should fix this: it adds a patch to validate appstream and includes release info.
