### ISSUE TITLE
RFE: Support JACK

### ISSUE THREAD

**Issue by jistr** [flathub/org.musescore.MuseScore#47]
It would be nice to support JACK backend, e.g. to be able to interconnect with Ardour (use Ardour to produce sounds instead of the internal synthesizer in MuseScore).

I wanted to post a PR and did some experimentation, but didn't manage to make MuseScore + JACK + Flatpak work. I compiled with JACK support successfully, but couldn't get the app to actually talk to JACK. There is a flatpak issue reported -- inability to share /dev/shm: https://github.com/flatpak/flatpak/issues/1509

So i tried just using a podman container with the RPM from Fedora, which is compiled with JACK support, and i can get podman to talk to JACK, but the distro package is compiled with Qt 5.12 instead of 5.9, and it causes the Palettes panel to render incorrectly (empty), making MuseScore completely unusable.

So the current choices on Fedora Silverblue are: RPM+Podman which connects to JACK but you can't edit the score at all, or Flatpak which can't connect to JACK. :expressionless: 

Last workaround would be to make a podman container where MuseScore is compiled from source, but i didn't want go down that rabbit hole.

**Comment by TingPing** [comment]
JACK simply isn't in Flatpak's future. If you want to try something you can test the current state of Pipewire.

**Comment by hfiguiere** [comment]
Apparently it is now until pipewire can replace it.

Flatpak 1.6.1 will allow shm for the devices.

**Comment by jistr** [comment]
Thanks!
