### ISSUE TITLE
"could not load Qt platform plugin"

### ISSUE THREAD

**Issue by sisterfelicity** [flathub/org.musescore.MuseScore#52]
Hi, all. I have just installed this on a Chromebook running Chrome OS 80, with an ARM processor. When I try to run it I get the following:

> No protocol specified
> qt.qpa.xcb: could not connect to display :99.0
> qt.qpa.plugin:: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, xcb.
> 

I did uninstall and reinstall, no good. 

I'd just really like to be able to use a more or less recent version of MuseScore on this Chromebook. But I haven't used Linux before, I don't understand the language, so all my trouble-shooting is more or less groping around blindfolded. So if someone here could give me some guidance on fixing that Qt platform plugin error, I'd be very grateful.

TIA

**Comment by jurf** [comment]
Try running `flatpak run --env=QT_QPA_PLATFORM=wayland` and see what happens. My guess is that `Xwayland` isn’t running.

**Comment by sisterfelicity** [comment]
Thanks, jurf. Please help me out with the syntax, I typed in just what you wrote and get back 

> APP must be specified

That must be totally obvious, right? But I'm a total Linux newbie -- where in that string do I specify the app? It's called musescore.

Thanks again

**Comment by jurf** [comment]
Sorry, I forgot to include it. :P Anyway, not totally obvious, no, it’s just a matter of learning to read the command line. I good trick is to call the troublesome command with the `--help` flag, e.g. `flatpak run --help`. If you try it, you’ll find at the top this:

```
$ flatpak run --help
Usage:
  flatpak run [OPTION?] APP [ARGUMENT?] - Run an app

[…]
```
APP is Flatpak jargon for an app ID, in this case `org.musescore.MuseScore`. Now you know where to put it:
```
$ flatpak run --env=QT_QPA_PLATFORM=wayland org.musescore.MuseScore
```

NB: if you see a `$` or a `#` as part of the command on the web, don’t include it, it’s just a symbol for the command prompt, with the dollar signalling a user prompt and the hash the root (super-user) prompt, i.e. you’ll need to prefix the command with `sudo` [SUperuser DO] login as root to run it correctly.

Don’t worry, the Linux world isn’t as frightning, as it seems, things have patterns and all of them are created by humans for humans, so they have a kind of inherent humanness to them. :-)

**Comment by sisterfelicity** [comment]
oh my goodness ... WEEKS I have been trying to get this app installed, I tried the appimage, the snap, the ubuntu webstore, and now all of a sudden I see a treble clef and 5 lines and notes! THANK YOU! I was about ready to finally trade in this old chromebook and upgrade my internet service, I truly didn't think I was going to be able to run it with my current setup. Thank you, thank you, flowers and chocolates to you!

**Comment by jurf** [comment]
I’m glad it works. Note that you are currently running in an experimental mode, so you might experience glitches. While we’re at it, mind testing if this works too?
```
$ flatpak run --env=QT_QPA_PLATFORM= org.musescore.MuseScore
```

**Comment by sisterfelicity** [comment]
Yes, that works, too! What's the difference?

**Comment by jurf** [comment]
Not a too big, the latter just lets the system choose the correct backend, just checking if it chooses correctly and thus allows a cleaner fix of this problem in the future. :-)

```
$ flatpak override --user --env=QT_QPA_PLATFORM= org.musescore.MuseScore
```
Should make the switch permanent, so you can launch MuseScore through traditional means (although I am unsure if Flatpak integrates into Chrome OS, but still, it’ll allow you to just do a `flatpak run org.musescore.MuseScore` without fiddling with command line options each time).

**Comment by sisterfelicity** [comment]
Sorry, I spoke too soon. It launched all right, nothing obviously wrong -- but since I haven't actually done anything in the app yet, who knows? But the terminal is showing all kinds of errors, and then it's just hanging up and not going back to the command prompt.
![image](https://user-images.githubusercontent.com/62124036/76749516-fa261380-6752-11ea-9b0e-3e1d10cd14ab.png)

**Comment by MarcSabatella** [comment]
I would assume it's normal that it wouldn't return to the command prompt until you actually exit the program.  That's standard for Linux as well as Windows etc,  Put a "&" at the end of the command line to get the command prompt back right away - the program being run is then considered to be in the "background".

Those status messages aren't necessarily a problem, unless you are finding something not working, un which case they will be useful debugging info.  MuseScore, like many other programs, spits out quite a few such messages to the terminal when run from the command line, you can ignore them normally.

**Comment by sisterfelicity** [comment]
Oh, good! So I've run that last "override" line jurf gave above, and once I try inputting some sheet music, I'll let you all know in a new thread -- I guess over at MuseScore to start out -- if anything doesn't work the way it seems like it should.

Thanks again

**Comment by hfiguiere** [comment]
> Sorry, I spoke too soon. It launched all right, nothing obviously wrong -- but since I haven't actually done anything in the app yet, who knows? But the terminal is showing all kinds of errors, and then it's just hanging up and not going back to the command prompt.
> ![image](https://user-images.githubusercontent.com/62124036/76749516-fa261380-6752-11ea-9b0e-3e1d10cd14ab.png)

I get the same error message on Fedora 32 x86_64. They don't prevent MuseScore from working. So they are not the problem.

**Comment by hfiguiere** [comment]
closing this. MuseScore is set to use xcb, has been for a while.
