### ISSUE TITLE
Application Crash reporting 

### ISSUE THREAD

**Issue by BrunoVernay** [flathub/org.musescore.MuseScore#82]
MuseScore crashes sometimes ... but GnomeAbrt is unable to report the crashes.
Is it a Flatpak issue? Is there some debug flag or something that could be set to enable crash reports??

--- Running report_uReport ---
Error: No segments found in coredump './coredump'
('report_uReport' exited with 1)

**Comment by hfiguiere** [comment]
Report to whom?

**Comment by BrunoVernay** [comment]
It means that using Flatpack does not allow to do crash report?
I would have to reproduce the crash with the RPM version to be able to report it?

**Comment by hfiguiere** [comment]
I also realize that it was build without debug symbols. This has been addressed. The stack trace should be more usefull.

**Comment by hfiguiere** [comment]
There is no standard mechanism with flatpak send crash reports. The manual process to collect the stack traces works.

There is no other specific action here.
