### ISSUE TITLE
Session management error

### ISSUE THREAD

**Issue by Crono23** [flathub/org.musescore.MuseScore#84]
After reinstalling Fedora, I tried running MuseScore to no avail.
So I tried running it with `flatpak run org.musescore.MuseScore` and it returned `Qt: Session management error: None of the authentication protocols specified are supported`

Any help? Thanks!

**Comment by hfiguiere** [comment]
works here on Fedora silverblue. Are you sure it's the Flathub version?

**Comment by hfiguiere** [comment]
Also, the application terminating immediately can be totally unrelated to these message and just be a crash.

**Comment by Crono23** [comment]
It's flatpak, here's the screenshot.
[https://www.dropbox.com/s/lum2v5ehel5558a/Screenshot%20from%202021-10-31%2012-23-34.png?dl=0](url)

I don't get why it'd crash on a fresh installation, it was fine before. I tried the RPM version and it runs fine.

**Comment by Mershl** [comment]
Fedora Silverblue 35. Same error here. Just crashes on startup on a fresh installation.

**Comment by hfiguiere** [comment]
The session management message is just a read herring. See #80

**Comment by Crono23** [comment]
The devs at MuseScore think the session management message is likely because of :

> Qt module is missing, like Qt WebEngine or maybe Qt Network Authorization, although ISTR that the latter is only needed for master (and the former only for 3.x and before)

I'd like to know the difference between Qt branch "5.15" and "5.15-21.08". The whole issue (MuseScore not launching) seems to appear after it was switched to "5.15-21.08". I also tried asking the MuseScore dev about it but all they said was MuseScore is supposed to run on Qt 5.9, but 5.15 should've been fine too.

**Comment by JohannPopper** [comment]
The problem persists on Fedora 36. Unfortunately, the "Qt: Session management error: None of the authentication protocols specified are supported" error is not a red herring, at least with regard to the solution discussed in #80. The font in question that is suggested to be removed isn't even installed by default in Fedora 36. I'm afraid this should not have been marked as closed. I myself can't see any reason why this flatpak should malfunction, but it certainly doesn't work on a range of my up-to-date Workstation and Silverblue computers, and the same with my colleagues. It's unfortunate Flathub has hosted a broken flatpak of a popular application on flatpaks' main distro for such a long time. I'm sorry I can't fix it.
