### ISSUE TITLE
Musescore flatpak breaks gnome-software on Fedora

### ISSUE THREAD

**Issue by sberla365** [flathub/org.musescore.MuseScore#91]
Hi, I installed MS flatpak in Fedora 36 using the workaround described in #80 
The app works really well but it breaks gnome-softare on Fedora 36.
There are two bug reports related to this topic: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1706
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1718
The issue doesn't appear when using the rpm version (which instead has other problems)

**Comment by hfiguiere** [comment]
Maybe GNOME software should be fixed too.

**Comment by hfiguiere** [comment]
both are closed. and the dupe is closed too.

again, if you can break the app that way then it needs to be fixed.
