### ISSUE TITLE
Musescore can't start

### ISSUE THREAD

**Issue by Enricone27** [flathub/org.musescore.MuseScore#95]
I installed Fedroa 36 and the Musescore 3.6.2 Flatpak and get an error:
`unknown:unknown: Qt: Session management error: None of the authentication protocols specified are supported`
the output with the -v flag
`F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/enrico/.local/share/flatpak
F: Opening user flatpak installation at path /home/enrico/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/enrico/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.15-21.08/3f92e49eb0d2f4b48b3b19537433316a331a5bcb39a6c300664725c0ce2a1fa9/files/lib32 does not exist
F: Cleaning up unused container id 2696787971
F: Cleaning up per-app-ID state for org.musescore.MuseScore
F: Allocated instance id 131462544
F: Add defaults in dir /org/musescore/MuseScore/
F: Add locks in dir /org/musescore/MuseScore/
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/enrico/.config/pulse/client.conf': Fehler beim Öffnen der Datei »/home/enrico/.config/pulse/client.conf«: Datei oder Verzeichnis nicht gefunden
F: Running 'bwrap --args 44 xdg-dbus-proxy --args=46'
F: Running 'bwrap --args 44 mscore'
unknown:unknown: Qt: Session management error: None of the authentication protocols specified are supported
`

**Comment by hfiguiere** [comment]
likely #80
